### ISSUE TITLE
Tests mas descriptivos

### ISSUE THREAD

**Issue by BrianCraig** [Proscripto/TP1-Rick_y_Morty#1]
Hola! 

Algunos tests tienen código similar al siguiente
```
	test "Rick - Experimentos para Realizar1" {
		const mochilaEsperado = #{ construirBateria, construirCircuito }
		assert.equals(mochilaEsperado,rick.experimentosQuePuedeRealizar())
	}
```

ahi hay una constante que se llama mochilaEsperando y no tiene sentido con el contexto, se podría llamar posiblesExperimentos, aunque en realidad no agrega nada la existencia de la constante.

directamente se podría usar como parametro del assert.

```
	test "Rick - Experimentos para Realizar1" {
		assert.equals(#{ construirBateria, construirCircuito },rick.experimentosQuePuedeRealizar())
	}
```

También el nombre podría directamente llamarse "Experimentos para Realizar" ya que esta en el contexto de Tests de Rick.

Saludos, Brian

**Comment by eacico** [comment]
Hola Brian
Quitamos las constantes que utilizamos para cargar la respuesta esperada segun tu sugerencia.
Ademas renombramos los tests para no repetir el nombre del describe al que pertenece.

Saludos, Esteban
