### ISSUE TITLE
Posible Template Method o Herencia en los Experimentos 

### ISSUE THREAD

**Issue by BrianCraig** [Proscripto/TP1-Rick_y_Morty#2]
Los los diferentes objetos que son experimentos tienen mucho comportamiento en común, principalmente en el mensaje realizar, habría que revisar y pensar una forma de simplificar estos hijos de Experimento.

De paso, construirCircuito no esta heredando de Experimento ;)

Un saludo, Brian

**Comment by eacico** [comment]
Ya lo ajustamos, de paso planteamos un reacomodamiento que imagino que nos dejaste picando para resolver solo el resultado de cada experimento en las subclases y el comportamiento del mensaje "realizar" en la superclase.
