### ISSUE TITLE
Recomendación: dividir RickYMorty.wlk en diferentes archivos

### ISSUE THREAD

**Issue by BrianCraig** [Proscripto/TP1-Rick_y_Morty#3]
RickYMorty.wlk contiene toda la implementación del TP, recomendaría ir dividiendo en archivos mas pequeños y usando la importación.

Saludos, Brian

**Comment by eacico** [comment]
Ya esta hecho, lo que originalemnte me parecio que estaba mas es hacer import desde un archivo y luego hacer el mismo import en otro archivo.
EJ:

    Archivo: "Experimentos.wlk"
        import Materiales.*

    Archivo: "Personajes.wlk"
        import Materiales.*
        import Experimentos.*

Perosi no lo haciamos de esta manera no funcionaba.
